---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "python"
  labels:
    funktion.fabric8.io/kind: "Runtime"
  annotations:
    fabric8.io/iconUrl: "https://funktion.fabric8.io/img/profile.png"
    funktion.fabric8.io/chromeDevTools: "true"
data:
  fileExtensions: "py"
  debugPort: "5858"
  deployment: |
    metadata:
      annotations:
        fabric8.io/iconUrl: "https://funktion.fabric8.io/img/profile.png"
      labels:
        kind: function
        name: hello
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            kind: function
            name: hello
        spec:
          terminationGracePeriodSeconds: 1
          containers:
          - image: jcrossley3/python-env:latest
            name: connector
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: source
                readOnly: true
                mountPath: /usr/src/app/funktion
            livenessProbe:
              httpGet:
                path: "/healthz"
                port: 8888
              initialDelaySeconds: 30
            readinessProbe:
              httpGet:
                path: "/healthz"
                port: 8888
              initialDelaySeconds: 2
          volumes:
          - name: source
            configMap:
              name: hello
              items:
              - key: source
                path: source.js
  service: |
    metadata:
      annotations:
        fabric8.io/iconUrl: "https://funktion.fabric8.io/img/profile.png"
    spec:
      ports:
      - port: 80
        targetPort: 8888
